/* eslint-disable import/no-anonymous-default-export */
export default {
	EMPLOYEE_LOAD_START: "USERS_LOAD_START",
	EMPLOYEE_LOAD_SUCCESS: "USERS_LOAD_SUCCESS",
	EMPLOYEE_LOAD_ERROR: "USERS_LOAD_ERROR",

    EMPLOYEE_DELETE_SUCCESS: "EMPLOYEE_DELETE_SUCCESS",
    EMPLOYEE_DELETE_ERROR: "EMPLOYEE_DELETE_ERROR",
	DELETE_EMPLOYEE_REQUEST: "DELETE_EMPLOYEE_REQUEST",

	EMPLOYEE_POST_START : "EMPLOYEE_POST_START",
	EMPLOYEE_POST_SUCCESS : "EMPLOYEE_POST_SUCCESS",
	EMPLOYEE_POST_ERROR : "EMPLOYEE_POST_ERROR",

	EMPLOYEE_EDIT_START : "EMPLOYEE_EDIT_START",
	EMPLOYEE_EDIT_SUCCESS : "EMPLOYEE_EDIT_SUCCESS",
	EMPLOYEE_EDIT_ERROR : "EMPLOYEE_EDIT_ERROR",

	

};